apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizfrontend
  namespace: quizfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizfrontend
  template:
    metadata:
      labels:
        app: quizfrontend
    spec:
      serviceAccountName: quizfrontend
      containers:
      - name: qfrontend
        image: 533675705859.dkr.ecr.us-west-2.amazonaws.com/quizfrontend:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: quizfrontend
